-   id: fmt
    name: fmt
    description: Format files with go fmt.
    entry: bash fmt.sh
    language: system
    files: \.go$
-   id: vet
    name: vet
    description: Check files with go vet.
    entry: bash vet.sh
    language: system
    files: \.go$
-   id: fix
    name: fix
    description: Fix files with go fix.
    entry: go fix
    language: system
    files: \.go$
